import type { PrototypeState, RoleSlug } from "./types";

export const roleBySlug = {
  admin: "ADMINISTRATEUR",
  company: "ENTREPRISE",
  audit: "AUDITEUR",
  investor: "INVESTISSEUR",
  researcher: "CHERCHEUR",
  institution: "INSTITUTION",
} as const;

export const slugByRole = {
  ADMINISTRATEUR: "admin",
  ENTREPRISE: "company",
  AUDITEUR: "audit",
  INVESTISSEUR: "investor",
  CHERCHEUR: "researcher",
  INSTITUTION: "institution",
} as const satisfies Record<(typeof roleBySlug)[RoleSlug], RoleSlug>;

export const roleLabels = {
  ADMINISTRATEUR: "Administrateur",
  ENTREPRISE: "Entreprise",
  AUDITEUR: "Auditeur",
  INVESTISSEUR: "Investisseur",
  CHERCHEUR: "Chercheur",
  INSTITUTION: "Institution",
} as const;

export function createInitialPrototypeState(): PrototypeState {
  return {
    users: [
      {
        id: "usr-admin",
        name: "Aminata Diallo",
        email: "admin@greenfinance.test",
        role: "ADMINISTRATEUR",
        organization: "GreenFinance-Scorer",
        status: "ACTIF",
        lastSeen: "Aujourd’hui, 09:42",
      },
      {
        id: "usr-company",
        name: "Sofia Martin",
        email: "esg@microsoft.test",
        role: "ENTREPRISE",
        organization: "Microsoft",
        entityId: "cmp-microsoft",
        status: "ACTIF",
        lastSeen: "Aujourd’hui, 08:15",
      },
      {
        id: "usr-auditor",
        name: "Lucas Bernard",
        email: "lucas@audit-climat.test",
        role: "AUDITEUR",
        organization: "Audit Climat Conseil",
        status: "ACTIF",
        lastSeen: "Hier, 17:28",
      },
      {
        id: "usr-investor",
        name: "Maya Chen",
        email: "maya@impact-capital.test",
        role: "INVESTISSEUR",
        organization: "Impact Capital",
        status: "ACTIF",
        lastSeen: "Aujourd’hui, 10:03",
      },
      {
        id: "usr-researcher",
        name: "Dr. Noah Kim",
        email: "noah@university.test",
        role: "CHERCHEUR",
        organization: "Université Verte",
        status: "ACTIF",
        lastSeen: "12 août 2026",
      },
      {
        id: "usr-institution",
        name: "Salma El Idrissi",
        email: "salma@icf.test",
        role: "INSTITUTION",
        organization: "Institut Climat & Finance",
        status: "ACTIF",
        lastSeen: "Aujourd’hui, 08:56",
      },
      {
        id: "usr-pending",
        name: "Élodie Moreau",
        email: "elodie@cabinet-rse.test",
        role: "AUDITEUR",
        organization: "Cabinet RSE",
        status: "INVITE",
        lastSeen: "Invitation envoyée",
      },
    ],
    companies: [
      {
        id: "cmp-microsoft",
        name: "Microsoft",
        website: "https://www.microsoft.com",
        logoUrl: "https://www.microsoft.com/favicon.ico",
        sector: "Technologies",
        country: "États-Unis",
        contact: "Sofia Martin",
        score: 82,
        environmental: 79,
        social: 84,
        governance: 85,
        scope1: 123_000,
        scope2: 89_000,
        scope3: 15_410_000,
        quality: "Élevée",
        published: true,
      },
      {
        id: "cmp-orsted",
        name: "Ørsted",
        website: "https://orsted.com",
        logoUrl: "https://orsted.com/favicon.ico",
        sector: "Énergies renouvelables",
        country: "Danemark",
        contact: "Freja Nielsen",
        score: 88,
        environmental: 93,
        social: 83,
        governance: 86,
        scope1: 1_540_000,
        scope2: 64_000,
        scope3: 5_820_000,
        quality: "Moyenne",
        published: true,
      },
      {
        id: "cmp-nova",
        name: "Nova Mobility",
        website: "https://nova-mobility.test",
        logoUrl: null,
        sector: "Mobilité",
        country: "France",
        contact: "Lina Petit",
        score: 71,
        environmental: 75,
        social: 72,
        governance: 66,
        scope1: 48_000,
        scope2: 21_000,
        scope3: 604_000,
        quality: "À confirmer",
        published: false,
      },
    ],
    reports: [
      {
        id: "rep-ms-2025",
        companyId: "cmp-microsoft",
        company: "Microsoft",
        title: "Environmental Sustainability Report 2025",
        year: 2025,
        status: "CORRECTION_DEMANDEE",
        auditor: "Lucas Bernard",
        completeness: 94,
        updatedAt: "20 août 2026, 09:18",
        opinion: "Réserves mineures sur le Scope 3, catégorie 1.",
        correctionNote: "Joindre la preuve détaillée du facteur d’émission Scope 3.",
        evidencePage: 3,
      },
      {
        id: "rep-orsted-2024",
        companyId: "cmp-orsted",
        company: "Ørsted",
        title: "Annual Report 2024",
        year: 2024,
        status: "PUBLIE",
        auditor: "Lucas Bernard",
        completeness: 98,
        updatedAt: "14 août 2026, 16:40",
        opinion: "Données cohérentes avec les preuves publiées.",
        correctionNote: null,
        evidencePage: 56,
      },
      {
        id: "rep-nova-2025",
        companyId: "cmp-nova",
        company: "Nova Mobility",
        title: "Rapport de durabilité 2025",
        year: 2025,
        status: "A_AFFECTER",
        auditor: null,
        completeness: 86,
        updatedAt: "19 août 2026, 13:05",
        opinion: null,
        correctionNote: null,
        evidencePage: 18,
      },
    ],
    positions: [
      {
        id: "pos-1",
        companyId: "cmp-microsoft",
        company: "Microsoft",
        amount: 420_000,
        currency: "EUR",
      },
      {
        id: "pos-2",
        companyId: "cmp-orsted",
        company: "Ørsted",
        amount: 280_000,
        currency: "EUR",
      },
    ],
    affiliations: [
      {
        id: "aff-1",
        institution: "Institut Climat & Finance",
        researcher: "Dr. Noah Kim",
        researcherEmail: "noah@university.test",
        status: "INVITE",
        primary: false,
      },
      {
        id: "aff-2",
        institution: "Observatoire ESG",
        researcher: "Dr. Noah Kim",
        researcherEmail: "noah@university.test",
        status: "ACTIF",
        primary: true,
      },
    ],
    analyses: [
      {
        id: "ana-1",
        title: "Décarbonation du secteur technologique",
        author: "Dr. Noah Kim",
        owner: "Personnel",
        companies: ["Microsoft", "Ørsted"],
        period: "2022–2025",
        status: "TERMINEE",
        updatedAt: "18 août 2026",
      },
      {
        id: "ana-2",
        title: "Qualité des données Scope 3",
        author: "Dr. Noah Kim",
        owner: "Institut Climat & Finance",
        companies: ["Microsoft"],
        period: "2024–2025",
        status: "BROUILLON",
        updatedAt: "20 août 2026",
      },
    ],
    methodology: {
      version: "v2.4",
      environmental: 40,
      social: 30,
      governance: 30,
      status: "ACTIVE",
    },
  };
}
