"""notification_id_ressource

Revision ID: 019f78ca4522
Revises: 82f1c49778a5
Create Date: 2026-09-12 22:19:43.658137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '019f78ca4522'
down_revision: Union[str, Sequence[str], None] = '82f1c49778a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('id_ressource', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'id_ressource')
    # ### end Alembic commands ###
