"""espace_investisseur_portefeuille_devise_et_archive

Revision ID: 43c724c6dda9
Revises: 00ade2db3f2f
Create Date: 2026-09-10 16:51:45.889257

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43c724c6dda9'
down_revision: str | Sequence[str] | None = '00ade2db3f2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portefeuille', sa.Column('devise_reference', sa.Enum('MRU', 'USD', 'EUR', name='deviseposition', native_enum=False, length=64), nullable=False))
    op.add_column('portefeuille', sa.Column('archive', sa.Boolean(), nullable=False))
    op.create_check_constraint('ck_position_portefeuille_montant_positif', 'position_portefeuille', 'montant_investi > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_position_portefeuille_montant_positif', 'position_portefeuille', type_='check')
    op.drop_column('portefeuille', 'archive')
    op.drop_column('portefeuille', 'devise_reference')
    # ### end Alembic commands ###
