"""phase5_contraintes_integrite_donnees

Revision ID: 4728c3ce1c36
Revises: 8c240a4a018f
Create Date: 2026-09-10 10:00:57.301186

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4728c3ce1c36'
down_revision: str | Sequence[str] | None = '8c240a4a018f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_donnee_carbone_pcaf_borne', 'donnee_carbone', 'score_qualite_pcaf BETWEEN 1 AND 5')
    op.create_check_constraint('ck_donnee_carbone_scope_valide', 'donnee_carbone', 'scope IN (1, 2, 3)')
    op.create_check_constraint('ck_donnee_carbone_valeur_non_negative', 'donnee_carbone', 'valeur_tonnes_co2e >= 0')
    op.create_unique_constraint('uq_rapport_esg_entreprise_checksum', 'rapport_esg', ['entreprise_id', 'checksum_sha256'])
    op.create_check_constraint('ck_score_esg_environnement_borne', 'score_esg', 'score_environnement BETWEEN 0 AND 100')
    op.create_check_constraint('ck_score_esg_gouvernance_borne', 'score_esg', 'score_gouvernance BETWEEN 0 AND 100')
    op.create_check_constraint('ck_score_esg_social_borne', 'score_esg', 'score_social BETWEEN 0 AND 100')
    op.create_check_constraint('ck_score_esg_valeur_globale_bornee', 'score_esg', 'valeur_globale BETWEEN 0 AND 100')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_score_esg_valeur_globale_bornee', 'score_esg', type_='check')
    op.drop_constraint('ck_score_esg_social_borne', 'score_esg', type_='check')
    op.drop_constraint('ck_score_esg_gouvernance_borne', 'score_esg', type_='check')
    op.drop_constraint('ck_score_esg_environnement_borne', 'score_esg', type_='check')
    op.drop_constraint('uq_rapport_esg_entreprise_checksum', 'rapport_esg', type_='unique')
    op.drop_constraint('ck_donnee_carbone_valeur_non_negative', 'donnee_carbone', type_='check')
    op.drop_constraint('ck_donnee_carbone_scope_valide', 'donnee_carbone', type_='check')
    op.drop_constraint('ck_donnee_carbone_pcaf_borne', 'donnee_carbone', type_='check')
    # ### end Alembic commands ###
