"""position_portefeuille_montant_converti_non_nullable

Revision ID: 4bec2363db7c
Revises: 43c724c6dda9
Create Date: 2026-09-10 17:00:43.016754

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4bec2363db7c'
down_revision: str | Sequence[str] | None = '43c724c6dda9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('position_portefeuille', 'montant_converti',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('position_portefeuille', 'montant_converti',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
