"""nom_fichier_origine_sur_rapport_esg

Revision ID: 7139d1346d91
Revises: 9118379d3bd0
Create Date: 2026-09-16 15:30:17.985116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7139d1346d91'
down_revision: Union[str, Sequence[str], None] = '9118379d3bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapport_esg', sa.Column('nom_fichier_origine', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapport_esg', 'nom_fichier_origine')
    # ### end Alembic commands ###
