"""institution_projet_perimetre_documents

Revision ID: 7589ab0b6fad
Revises: 019f78ca4522
Create Date: 2026-09-14 11:10:36.630262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7589ab0b6fad'
down_revision: Union[str, Sequence[str], None] = '019f78ca4522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_FK_RAPPORT_NAME = 'fk_analyse_entreprise_rapport_id_rapport_esg'
_FK_SCORE_NAME = 'fk_analyse_entreprise_score_esg_id_score_esg'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet_entreprise',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('projet_id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projet_id', 'entreprise_id', name='uq_projet_entreprise')
    )
    op.create_table('projet_document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('projet_id', sa.Uuid(), nullable=False),
    sa.Column('rapport_id', sa.Uuid(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapport_esg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projet_id', 'rapport_id', name='uq_projet_document')
    )
    op.add_column('analyse_entreprise', sa.Column('rapport_id', sa.Uuid(), nullable=True))
    op.add_column('analyse_entreprise', sa.Column('score_esg_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(_FK_RAPPORT_NAME, 'analyse_entreprise', 'rapport_esg', ['rapport_id'], ['id'])
    op.create_foreign_key(_FK_SCORE_NAME, 'analyse_entreprise', 'score_esg', ['score_esg_id'], ['id'])
    op.add_column('chercheur_institution', sa.Column('conditions_collaboration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projet', sa.Column('objectif', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projet', sa.Column('date_debut', sa.DateTime(), nullable=True))
    op.add_column('projet', sa.Column('date_fin_prevue', sa.DateTime(), nullable=True))
    op.add_column('projet', sa.Column('date_limite', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_score_esg_rapport_configuration', 'score_esg', ['rapport_id', 'configuration_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_score_esg_rapport_configuration', 'score_esg', type_='unique')
    op.drop_column('projet', 'date_limite')
    op.drop_column('projet', 'date_fin_prevue')
    op.drop_column('projet', 'date_debut')
    op.drop_column('projet', 'objectif')
    op.drop_column('chercheur_institution', 'conditions_collaboration')
    op.drop_constraint(_FK_SCORE_NAME, 'analyse_entreprise', type_='foreignkey')
    op.drop_constraint(_FK_RAPPORT_NAME, 'analyse_entreprise', type_='foreignkey')
    op.drop_column('analyse_entreprise', 'score_esg_id')
    op.drop_column('analyse_entreprise', 'rapport_id')
    op.drop_table('projet_document')
    op.drop_table('projet_entreprise')
    # ### end Alembic commands ###
