"""date_affectation_sur_rapport

Revision ID: 8c240a4a018f
Revises: cc458b3b8aa4
Create Date: 2026-09-09 15:42:45.987475

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c240a4a018f'
down_revision: str | Sequence[str] | None = 'cc458b3b8aa4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapport_esg', sa.Column('date_affectation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapport_esg', 'date_affectation')
    # ### end Alembic commands ###
