"""score_global_declare_sur_rapport_esg

Revision ID: 9118379d3bd0
Revises: 23130834a4d6
Create Date: 2026-09-16 14:13:05.803874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9118379d3bd0'
down_revision: Union[str, Sequence[str], None] = '23130834a4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapport_esg', sa.Column('score_global_declare', sa.Float(), nullable=True))
    op.add_column('rapport_esg', sa.Column('score_global_declare_preuve_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'rapport_esg', 'preuve_documentaire', ['score_global_declare_preuve_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rapport_esg', type_='foreignkey')
    op.drop_column('rapport_esg', 'score_global_declare_preuve_id')
    op.drop_column('rapport_esg', 'score_global_declare')
    # ### end Alembic commands ###
