"""espace_chercheur_institution_projets_analyses

Revision ID: b5a5ddf26c9a
Revises: 4bec2363db7c
Create Date: 2026-09-10 17:36:24.614878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5a5ddf26c9a'
down_revision: Union[str, Sequence[str], None] = '4bec2363db7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('statut', sa.Enum('OUVERT', 'CLOTURE', name='statutprojet', native_enum=False, length=64), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affectation_projet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('projet_id', sa.Uuid(), nullable=False),
    sa.Column('chercheur_id', sa.Uuid(), nullable=False),
    sa.Column('date_affectation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chercheur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projet_id', 'chercheur_id', name='uq_affectation_projet_chercheur')
    )
    op.create_table('analyse',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('projet_id', sa.Uuid(), nullable=False),
    sa.Column('chercheur_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'SOUMISE', 'VALIDEE', 'CORRECTION_DEMANDEE', name='statutanalyse', native_enum=False, length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('analyse_precedente_id', sa.Uuid(), nullable=True),
    sa.Column('commentaire_institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('date_decision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyse_precedente_id'], ['analyse.id'], ),
    sa.ForeignKeyConstraint(['chercheur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyse_entreprise',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analyse_id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyse.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analyse_id', 'entreprise_id', name='uq_analyse_entreprise')
    )
    op.add_column('chercheur_institution', sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACCEPTE', 'REFUSE', name='statutrattachement', native_enum=False, length=64), nullable=False))
    op.add_column('chercheur_institution', sa.Column('date_invitation', sa.DateTime(), nullable=False))
    op.add_column('chercheur_institution', sa.Column('date_reponse', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_chercheur_institution', 'chercheur_institution', ['chercheur_id', 'institution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chercheur_institution', 'chercheur_institution', type_='unique')
    op.drop_column('chercheur_institution', 'date_reponse')
    op.drop_column('chercheur_institution', 'date_invitation')
    op.drop_column('chercheur_institution', 'statut')
    op.drop_table('analyse_entreprise')
    op.drop_table('analyse')
    op.drop_table('affectation_projet')
    op.drop_table('projet')
    # ### end Alembic commands ###
