"""schema pivot complet (Etape 3)

Revision ID: b5f953dddf56
Revises: 440af0be0e05
Create Date: 2026-08-12 10:53:17.878580

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5f953dddf56'
down_revision: str | Sequence[str] | None = '440af0be0e05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preuve_documentaire',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom_document', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('nombre_pages_total', sa.Integer(), nullable=False),
    sa.Column('page_debut', sa.Integer(), nullable=False),
    sa.Column('page_fin', sa.Integer(), nullable=False),
    sa.Column('pdf_extrait_genere', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mot_de_passe_hache', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATEUR', 'ENTREPRISE', 'AUDITEUR', 'INVESTISSEUR', 'CHERCHEUR', 'INSTITUTION', name='role', native_enum=False, length=64), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_table('chercheur_institution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chercheur_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chercheur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_ponderation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fichier_yaml', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entreprise',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secteur', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pays', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_officiel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=True),
    sa.Column('montant_minimum_investissement', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution_profil',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('quota_export', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portefeuille',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investisseur_id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investisseur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_portefeuille',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portefeuille_id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('montant_investi', sa.Float(), nullable=False),
    sa.Column('devise', sa.Enum('MRU', 'USD', 'EUR', name='deviseposition', native_enum=False, length=64), nullable=False),
    sa.Column('taux_change_utilise', sa.Float(), nullable=True),
    sa.Column('montant_converti', sa.Float(), nullable=True),
    sa.Column('type_duree', sa.Enum('OUVERTE', 'FIXE', name='typedureeinvestissement', native_enum=False, length=64), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['portefeuille_id'], ['portefeuille.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapport_esg',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('RAPPORT_ANNUEL', 'RAPPORT_ESG', 'RAPPORT_CLIMAT', name='typerapport', native_enum=False, length=64), nullable=False),
    sa.Column('canal', sa.Enum('AUTOMATIQUE', 'ENTREPRISE', name='canaldepot', native_enum=False, length=64), nullable=False),
    sa.Column('date_depot', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Enum('ENVOYE', 'EN_EXTRACTION', 'AFFECTE_AUDITEUR', 'EN_VALIDATION', 'VALIDE', 'REJETE', 'DEMANDE_CORRECTION', name='statutrapport', native_enum=False, length=64), nullable=False),
    sa.Column('fichier_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auditeur_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['auditeur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avis_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rapport_id', sa.Uuid(), nullable=False),
    sa.Column('auditeur_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('RECOMMANDE_VALIDATION', 'ANOMALIE_SIGNALEE', name='decisionaudit', native_enum=False, length=64), nullable=False),
    sa.Column('commentaire', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_avis', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auditeur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapport_esg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donnee_carbone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rapport_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('categorie_ges', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valeur_tonnes_co2e', sa.Float(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('methode', sa.Enum('RAPPORTEE', 'ESTIMEE', 'CALCULEE', name='methodedonnee', native_enum=False, length=64), nullable=False),
    sa.Column('score_qualite_pcaf', sa.Integer(), nullable=False),
    sa.Column('preuve_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['preuve_id'], ['preuve_documentaire.id'], ),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapport_esg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicateur_esg',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rapport_id', sa.Uuid(), nullable=False),
    sa.Column('pilier', sa.Enum('ENVIRONNEMENT', 'SOCIAL', 'GOUVERNANCE', name='pilier', native_enum=False, length=64), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('unite', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('methode', sa.Enum('RAPPORTEE', 'ESTIMEE', 'CALCULEE', name='methodedonnee', native_enum=False, length=64), nullable=False),
    sa.Column('preuve_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['preuve_id'], ['preuve_documentaire.id'], ),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapport_esg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_esg',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rapport_id', sa.Uuid(), nullable=False),
    sa.Column('configuration_id', sa.Uuid(), nullable=False),
    sa.Column('valeur_globale', sa.Float(), nullable=False),
    sa.Column('score_environnement', sa.Float(), nullable=False),
    sa.Column('score_social', sa.Float(), nullable=False),
    sa.Column('score_gouvernance', sa.Float(), nullable=False),
    sa.Column('date_calcul', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration_ponderation.id'], ),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapport_esg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signalement_ecart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicateur_id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('nature_ecart', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_signalement', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['indicateur_id'], ['indicateur_esg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signalement_ecart')
    op.drop_table('score_esg')
    op.drop_table('indicateur_esg')
    op.drop_table('donnee_carbone')
    op.drop_table('avis_audit')
    op.drop_table('rapport_esg')
    op.drop_table('position_portefeuille')
    op.drop_table('portefeuille')
    op.drop_table('notification')
    op.drop_table('institution_profil')
    op.drop_table('entreprise')
    op.drop_table('configuration_ponderation')
    op.drop_table('chercheur_institution')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('preuve_documentaire')
    # ### end Alembic commands ###
