"""date_publication_sur_entreprise

Revision ID: b60e8622e4d7
Revises: d43c178f8501
Create Date: 2026-09-01 13:36:32.568828

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b60e8622e4d7'
down_revision: str | Sequence[str] | None = 'd43c178f8501'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('date_publication', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprise', 'date_publication')
    # ### end Alembic commands ###
