"""entreprise_devise_montant_minimum

Revision ID: d00548652232
Revises: b5a5ddf26c9a
Create Date: 2026-09-11 13:59:01.098543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd00548652232'
down_revision: Union[str, Sequence[str], None] = 'b5a5ddf26c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('devise_montant_minimum', sa.Enum('MRU', 'USD', 'EUR', name='deviseposition', native_enum=False, length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprise', 'devise_montant_minimum')
    # ### end Alembic commands ###
