"""extraction_terminee_le_et_erreur_sur_rapport_esg

Revision ID: d43c178f8501
Revises: b5f953dddf56
Create Date: 2026-09-01 12:23:16.889629

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd43c178f8501'
down_revision: str | Sequence[str] | None = 'b5f953dddf56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapport_esg', sa.Column('extraction_terminee_le', sa.DateTime(), nullable=True))
    op.add_column('rapport_esg', sa.Column('extraction_erreur', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapport_esg', 'extraction_erreur')
    op.drop_column('rapport_esg', 'extraction_terminee_le')
    # ### end Alembic commands ###
